apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
      matchLabels:
        app.kubernetes.io/name: reverseproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reverseproxy
    spec:
      containers:
      - image: mohamedelmowafy/mowafy-reverseproxy:v1
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always
